
# This Workflow is to create branch protection rules for the master branch
name: Create Branch Protection Rules

# Action runs on issue pin
on: 
    push
#  issues:
#     types: [pinned]


jobs:
    createsBranchProtection:
        runs-on: ubuntu-latest
        steps:
        - name: Branch Guardian 
          uses: infamous-riddles/branch-guardian@v1
          with: 
            PERSONAL-ACCESS-TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
            BASE-BRANCH-PATTERN: 'master'
            REQUIRED-NUMBER-OF-REVIEWERS: 1
            REQUIRE-REVIEW-FROM-CODEOWNERS: 'true'
